networks:
  localstack-network:
services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - PERSISTENCE=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SKIP_INFRA_DOWNLOADS=1
    volumes:
      - './data:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - localstack-network

  runner:
    build:
      context: .
      dockerfile: terraform-runner.Dockerfile

    container_name: runner
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: ['sh', '-c', '../scripts/tflocal.sh']
    depends_on:
      - dev-tools
    networks:
      - localstack-network
