version: '3.8'
services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - PERSISTENCE=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SKIP_INFRA_DOWNLOADS=1
    volumes:
      - './localstack-data:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
