networks:
  localstack-network:

services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3,dynamodb,kms,iam
      - DEBUG=1
      - PERSISTENCE=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SKIP_INFRA_DOWNLOADS=1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - localstack-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  terraform-local-runner:
    build:
      context: ./terraform-runner
    container_name: terraform-local-runner
    working_dir: /infrastructure
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - LOCALSTACK_HOST=localstack
      - HOSTNAME_EXTERNAL=localstack
      - LOCALSTACK_HOSTNAME=localstack
      - S3_HOSTNAME=localstack
      - TF_VAR_s3_use_path_style=true
      - AWS_DEFAULT_REGION=us-west-1
    volumes:
      - '../envs:/envs'
      - '../infra:/infrastructure'
      - './terraform-runner/scripts/deploy.sh:/deploy.sh'
    entrypoint: ['/deploy.sh']
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - localstack-network
    restart: 'no'

  infra-provisioning-tests:
    depends_on:
      terraform-local-runner:
        condition: service_completed_successfully

    build:
      context: ./infra-provisioning-test
    volumes:
      - './infra-provisioning-test/tests:/tests'
    profiles: [test]
    working_dir: /tests
    command: pytest infra/

    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    networks:
      - localstack-network
